### ISSUE TITLE
Referees (BraveHearts)

### ISSUE THREAD

**Issue by RubeGamerV** [BraveHearts/Revisiones#9]
Añadidos:
- RubeGamerV
- MCChull
- AsdeMC
- NocturnalBoy

**Comment by AsdeMC** [comment]
auuuuuuuuuuuuuuuuuuuuuuuuuuuauauauauauauuuuuuuuuuuuuuuuuu

**Comment by MCChull** [comment]
Favor de agregar a HackerHDPRO, sub capitan del team

**Comment by RubeGamerV** [comment]
Agregado!

**Comment by RubeGamerV** [comment]
Añadido:
-HackerHDPRO
